tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# All in one for **env
brew "anyenv"
# Official Amazon AWS command-line interface
brew "awscli"
# Load/unload environment variables based on $PWD
brew "direnv"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Lazier way to manage everything docker
brew "lazydocker"
# Adds an OCR text layer to scanned PDF files
brew "ocrmypdf"
# Development kit for the Java programming language
brew "openjdk@11"
# Show ps output as a tree
brew "pstree"
# Safe, concurrent, practical language
brew "rust"
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# SDK
brew "dart-lang/dart/dart"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application launcher and productivity software
cask "alfred"
# Memory training application
cask "anki"
# Clipboard extension app
cask "clipy"
# Trains AIs to understand and translate texts
cask "deepl"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-noto-sans-gothic"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
cask "google-japanese-ime"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Software for Logitech devices
cask "logitech-options"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Visual tool to design, develop and administer MySQL servers
cask "mysqlworkbench"
# Developer IDE or Management Environment for Neo4j instances
cask "neo4j"
# GUI tool and IDE for MongoDB
cask "nosqlbooster-for-mongodb"
# App to write, plan, collaborate, and get organized
cask "notion"
# MySQL/MariaDB database management
cask "sequel-ace"
# Team communication and collaboration software
cask "slack"
# IDE, client, and GUI for MongoDB
cask "studio-3t"
# Native GUI tool for relational databases
cask "tableplus"
# Tool for creating dynamic digital art
cask "touchdesigner"
# Development environment
cask "vagrant"
# Free and open-source hosted hypervisor for x86 virtualization
cask "virtualbox"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
